table _Measures
	isHidden
	lineageTag: me000008-0000-0000-0000-000000000001


	measure 'Total Sales' = SUM(FactSales[TotalAmount])
		formatString: $ #,##0
		lineageTag: me000008-0101-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Total Cost' =
			SUMX(
			    FactSales,
			    RELATED(DimProduct[CostPrice]) * FactSales[Quantity]
			)
		formatString: $ #,##0
		lineageTag: me000008-0102-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Gross Profit' = [Total Sales] - [Total Cost]
		formatString: $ #,##0
		lineageTag: me000008-0103-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Sales])
		formatString: 0.0%
		lineageTag: me000008-0104-0000-0000-000000000001

	measure 'Total Quantity Sold' = SUM(FactSales[Quantity])
		formatString: #,##0
		lineageTag: me000008-0105-0000-0000-000000000001

	measure 'Order Count' = DISTINCTCOUNT(FactSales[SalesID])
		formatString: #,##0
		lineageTag: me000008-0106-0000-0000-000000000001

	measure 'Average Order Value' = DIVIDE([Total Sales], [Order Count])
		formatString: $ #,##0.00
		lineageTag: me000008-0107-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Average Selling Price' = DIVIDE([Total Sales], [Total Quantity Sold])
		formatString: $ #,##0.00
		lineageTag: me000008-0108-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Discount Amount' = SUM(FactSales[DiscountAmount])
		formatString: $ #,##0
		lineageTag: me000008-0109-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Effective Discount Rate %' =
			DIVIDE(
			    [Discount Amount],
			    [Total Sales] + [Discount Amount]
			)
		formatString: 0.0%
		lineageTag: me000008-0110-0000-0000-000000000001

	measure 'Net Sales' = [Total Sales] - [Return Amount]
		formatString: $ #,##0
		lineageTag: me000008-0111-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Net Margin %' =
			DIVIDE(
			    [Gross Profit] - [Return Amount],
			    [Total Sales]
			)
		formatString: 0.0%
		lineageTag: me000008-0112-0000-0000-000000000001


	measure 'Sales MTD' =
			CALCULATE([Total Sales], DATESMTD(DimDate[Date]))
		formatString: $ #,##0
		lineageTag: me000008-0201-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Sales QTD' =
			CALCULATE([Total Sales], DATESQTD(DimDate[Date]))
		formatString: $ #,##0
		lineageTag: me000008-0202-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Sales YTD' =
			CALCULATE([Total Sales], DATESYTD(DimDate[Date]))
		formatString: $ #,##0
		lineageTag: me000008-0203-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Sales Prior Month' =
			CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, MONTH))
		formatString: $ #,##0
		lineageTag: me000008-0204-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Sales Prior Quarter' =
			CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, QUARTER))
		formatString: $ #,##0
		lineageTag: me000008-0205-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Sales Prior Year' =
			CALCULATE([Total Sales], DATEADD(DimDate[Date], -1, YEAR))
		formatString: $ #,##0
		lineageTag: me000008-0206-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Rolling 3M Sales' =
			CALCULATE(
			    [Total Sales],
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -3, MONTH)
			)
		formatString: $ #,##0
		lineageTag: me000008-0207-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Rolling 12M Sales' =
			CALCULATE(
			    [Total Sales],
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -12, MONTH)
			)
		formatString: $ #,##0
		lineageTag: me000008-0208-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}


	measure 'MoM Sales Growth %' =
			DIVIDE(
			    [Total Sales] - [Sales Prior Month],
			    [Sales Prior Month]
			)
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: me000008-0301-0000-0000-000000000001

	measure 'QoQ Sales Growth %' =
			DIVIDE(
			    [Total Sales] - [Sales Prior Quarter],
			    [Sales Prior Quarter]
			)
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: me000008-0302-0000-0000-000000000001

	measure 'YoY Sales Growth %' =
			DIVIDE(
			    [Total Sales] - [Sales Prior Year],
			    [Sales Prior Year]
			)
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: me000008-0303-0000-0000-000000000001

	measure 'Profit YTD' =
			CALCULATE([Gross Profit], DATESYTD(DimDate[Date]))
		formatString: $ #,##0
		lineageTag: me000008-0304-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Profit Prior Year' =
			CALCULATE([Gross Profit], DATEADD(DimDate[Date], -1, YEAR))
		formatString: $ #,##0
		lineageTag: me000008-0305-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'YoY Profit Growth %' =
			DIVIDE(
			    [Gross Profit] - [Profit Prior Year],
			    [Profit Prior Year]
			)
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: me000008-0306-0000-0000-000000000001

	measure 'YTD vs Prior YTD %' =
			DIVIDE(
			    [Sales YTD],
			    CALCULATE([Sales YTD], DATEADD(DimDate[Date], -1, YEAR))
			)
		formatString: 0.0%
		lineageTag: me000008-0307-0000-0000-000000000001


	measure 'Total Returns' = DISTINCTCOUNT(FactReturns[ReturnID])
		formatString: #,##0
		lineageTag: me000008-0401-0000-0000-000000000001

	measure 'Return Amount' = SUM(FactReturns[RefundAmount])
		formatString: $ #,##0
		lineageTag: me000008-0402-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Return Rate %' =
			DIVIDE([Total Returns], [Order Count])
		formatString: 0.0%
		lineageTag: me000008-0403-0000-0000-000000000001

	measure 'Return Amount Rate %' =
			DIVIDE([Return Amount], [Total Sales])
		formatString: 0.0%
		lineageTag: me000008-0404-0000-0000-000000000001

	measure 'YoY Return Rate Change' =
			[Return Rate %]
			    - CALCULATE([Return Rate %], DATEADD(DimDate[Date], -1, YEAR))
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: me000008-0405-0000-0000-000000000001


	measure 'Total Customers' = DISTINCTCOUNT(FactSales[CustomerID])
		formatString: #,##0
		lineageTag: me000008-0501-0000-0000-000000000001

	measure 'Active Customers (90d)' =
			CALCULATE(
			    DISTINCTCOUNT(FactSales[CustomerID]),
			    DATESINPERIOD(DimDate[Date], LASTDATE(DimDate[Date]), -90, DAY)
			)
		formatString: #,##0
		lineageTag: me000008-0502-0000-0000-000000000001

	measure 'New Customers' =
			CALCULATE(
			    DISTINCTCOUNT(DimCustomer[CustomerID]),
			    FILTER(
			        DimCustomer,
			        YEAR(DimCustomer[JoinDate]) = YEAR(MAX(DimDate[Date]))
			            && MONTH(DimCustomer[JoinDate]) = MONTH(MAX(DimDate[Date]))
			    )
			)
		formatString: #,##0
		lineageTag: me000008-0503-0000-0000-000000000001

	measure 'Customer Retention Rate %' =
			DIVIDE([Active Customers (90d)], [Total Customers])
		formatString: 0.0%
		lineageTag: me000008-0504-0000-0000-000000000001

	measure 'Avg Revenue Per Customer' =
			DIVIDE([Total Sales], [Total Customers])
		formatString: $ #,##0
		lineageTag: me000008-0505-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Revenue Per Active Customer' =
			DIVIDE([Total Sales], [Active Customers (90d)])
		formatString: $ #,##0
		lineageTag: me000008-0506-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Repeat Customers' =
			CALCULATE(
			    DISTINCTCOUNT(FactSales[CustomerID]),
			    FILTER(
			        VALUES(FactSales[CustomerID]),
			        CALCULATE(DISTINCTCOUNT(FactSales[SalesID])) > 1
			    )
			)
		formatString: #,##0
		lineageTag: me000008-0507-0000-0000-000000000001

	measure 'Repeat Rate %' =
			DIVIDE([Repeat Customers], [Total Customers])
		formatString: 0.0%
		lineageTag: me000008-0508-0000-0000-000000000001

	measure 'Top 10 Customer Concentration %' =
			DIVIDE(
			    CALCULATE(
			        [Total Sales],
			        TOPN(10, VALUES(DimCustomer[CustomerID]), [Total Sales])
			    ),
			    [Total Sales]
			)
		formatString: 0.0%
		lineageTag: me000008-0509-0000-0000-000000000001

	measure 'Avg Orders Per Customer' =
			DIVIDE([Order Count], [Total Customers])
		formatString: #,##0.0
		lineageTag: me000008-0510-0000-0000-000000000001


	measure 'Products Sold' = DISTINCTCOUNT(FactSales[ProductID])
		formatString: #,##0
		lineageTag: me000008-0601-0000-0000-000000000001

	measure 'Product Contribution %' =
			DIVIDE(
			    [Total Sales],
			    CALCULATE([Total Sales], ALL(DimProduct))
			)
		formatString: 0.0%
		lineageTag: me000008-0602-0000-0000-000000000001

	measure 'Avg Units Per Order' =
			DIVIDE([Total Quantity Sold], [Order Count])
		formatString: #,##0.0
		lineageTag: me000008-0603-0000-0000-000000000001

	measure 'Product Return Rate %' =
			DIVIDE(
			    DISTINCTCOUNT(FactReturns[ReturnID]),
			    [Order Count]
			)
		formatString: 0.0%
		lineageTag: me000008-0604-0000-0000-000000000001

	measure 'Avg List Price' =
			CALCULATE(AVERAGE(DimProduct[UnitPrice]), ALL(FactSales))
		formatString: $ #,##0.00
		lineageTag: me000008-0605-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Price Realization %' =
			DIVIDE([Average Selling Price], [Avg List Price])
		formatString: 0.0%
		lineageTag: me000008-0606-0000-0000-000000000001

	measure 'Product Gross Margin %' =
			DIVIDE(
			    SUMX(
			        FactSales,
			        (RELATED(DimProduct[UnitPrice]) - RELATED(DimProduct[CostPrice]))
			            * FactSales[Quantity]
			    ),
			    SUMX(
			        FactSales,
			        RELATED(DimProduct[UnitPrice]) * FactSales[Quantity]
			    )
			)
		formatString: 0.0%
		lineageTag: me000008-0607-0000-0000-000000000001

	measure 'Category Sales Rank' =
			RANKX(
			    ALL(DimProduct[Category]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		lineageTag: me000008-0608-0000-0000-000000000001


	measure 'Current Stock' = SUM(FactInventory[QuantityOnHand])
		formatString: #,##0
		lineageTag: me000008-0701-0000-0000-000000000001

	measure 'Stock on Order' = SUM(FactInventory[QuantityOnOrder])
		formatString: #,##0
		lineageTag: me000008-0702-0000-0000-000000000001

	measure 'Avg Monthly Usage' = AVERAGE(FactInventory[MonthlyUsage])
		formatString: #,##0
		lineageTag: me000008-0703-0000-0000-000000000001

	measure 'Days of Supply' =
			DIVIDE(
			    [Current Stock],
			    DIVIDE([Avg Monthly Usage], 30)
			)
		formatString: #,##0.0
		lineageTag: me000008-0704-0000-0000-000000000001

	measure 'Stockout Products' =
			CALCULATE(
			    DISTINCTCOUNT(FactInventory[ProductID]),
			    FILTER(FactInventory, FactInventory[QuantityOnHand] = 0)
			)
		formatString: #,##0
		lineageTag: me000008-0705-0000-0000-000000000001


	measure 'Region Sales %' =
			DIVIDE(
			    [Total Sales],
			    CALCULATE([Total Sales], ALL(DimRegion))
			)
		formatString: 0.0%
		lineageTag: me000008-0801-0000-0000-000000000001

	measure 'Active Regions' = DISTINCTCOUNT(FactSales[RegionID])
		formatString: #,##0
		lineageTag: me000008-0802-0000-0000-000000000001

	measure 'Sales per Region' =
			DIVIDE([Total Sales], [Active Regions])
		formatString: $ #,##0
		lineageTag: me000008-0803-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Target Attainment %' =
			DIVIDE(
			    [Total Sales],
			    SUM(DimRegion[SalesTarget])
			)
		formatString: 0.0%
		lineageTag: me000008-0804-0000-0000-000000000001


	measure 'Sales % of Total' =
			DIVIDE(
			    [Total Sales],
			    CALCULATE([Total Sales], ALL())
			)
		formatString: 0.0%
		lineageTag: me000008-0901-0000-0000-000000000001

	measure 'Product Sales Rank' =
			RANKX(
			    ALL(DimProduct[ProductName]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		lineageTag: me000008-0902-0000-0000-000000000001

	measure 'Customer Sales Rank' =
			RANKX(
			    ALL(DimCustomer[CustomerName]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		lineageTag: me000008-0903-0000-0000-000000000001

	measure 'Cumulative Sales %' =
			VAR CurrentRank = [Product Sales Rank]
			RETURN
			CALCULATE(
			    [Sales % of Total],
			    FILTER(
			        ALL(DimProduct[ProductName]),
			        [Product Sales Rank] <= CurrentRank
			    )
			)
		formatString: 0.0%
		lineageTag: me000008-0904-0000-0000-000000000001

	measure 'Sales Velocity (Daily)' =
			DIVIDE(
			    [Total Sales],
			    CALCULATE(
			        DISTINCTCOUNT(DimDate[DateID]),
			        CROSSJOIN(
			            VALUES(DimDate[DateID]),
			            FILTER(VALUES(FactSales[SalesID]), NOT(ISBLANK([Total Sales])))
			        )
			    )
			)
		formatString: $ #,##0
		lineageTag: me000008-0905-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Weekend Sales' =
			CALCULATE([Total Sales], DimDate[IsWeekend] = TRUE)
		formatString: $ #,##0
		lineageTag: me000008-0906-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	measure 'Weekday Sales' =
			CALCULATE([Total Sales], DimDate[IsWeekend] = FALSE)
		formatString: $ #,##0
		lineageTag: me000008-0907-0000-0000-000000000001

		annotation PBI_FormatHint = {"currencySymbol":"$"}

	partition '_Measures-Partition' = m
		mode: import
		source =
				let
				    Source = #table(type table [], {})
				in
				    Source

	annotation PBI_ResultType = Table
