table DimCustomer
	lineageTag: cu000002-0000-0000-0000-000000000001

	column CustomerID
		dataType: string
		lineageTag: cu000002-0001-0000-0000-000000000001
		sourceColumn: CustomerID
		summarizeBy: none

	column CustomerName
		dataType: string
		lineageTag: cu000002-0002-0000-0000-000000000001
		sourceColumn: CustomerName
		summarizeBy: none

	column Country
		dataType: string
		lineageTag: cu000002-0003-0000-0000-000000000001
		sourceColumn: Country
		summarizeBy: none

	column City
		dataType: string
		lineageTag: cu000002-0004-0000-0000-000000000001
		sourceColumn: City
		summarizeBy: none

	column JoinDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: cu000002-0005-0000-0000-000000000001
		sourceColumn: JoinDate
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: cu000002-0006-0000-0000-000000000001
		sourceColumn: Segment
		summarizeBy: none

	column Industry
		dataType: string
		lineageTag: cu000002-0007-0000-0000-000000000001
		sourceColumn: Industry
		summarizeBy: none

	column AcquisitionChannel
		dataType: string
		lineageTag: cu000002-0008-0000-0000-000000000001
		sourceColumn: AcquisitionChannel
		summarizeBy: none

	column RegionID
		dataType: int64
		isHidden
		lineageTag: cu000002-0009-0000-0000-000000000001
		sourceColumn: RegionID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'DimCustomer-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "customers.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"CustomerID",         type text},
				        {"CustomerName",       type text},
				        {"Country",            type text},
				        {"City",               type text},
				        {"JoinDate",           type date},
				        {"Segment",            type text},
				        {"Industry",           type text},
				        {"AcquisitionChannel", type text},
				        {"RegionID",           Int64.Type}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
