table DimProduct
	lineageTag: pr000003-0000-0000-0000-000000000001

	column ProductID
		dataType: string
		lineageTag: pr000003-0001-0000-0000-000000000001
		sourceColumn: ProductID
		summarizeBy: none

	column ProductName
		dataType: string
		lineageTag: pr000003-0002-0000-0000-000000000001
		sourceColumn: ProductName
		summarizeBy: none

	column Category
		dataType: string
		lineageTag: pr000003-0003-0000-0000-000000000001
		sourceColumn: Category
		summarizeBy: none

	column Subcategory
		dataType: string
		lineageTag: pr000003-0004-0000-0000-000000000001
		sourceColumn: Subcategory
		summarizeBy: none

	column Brand
		dataType: string
		lineageTag: pr000003-0005-0000-0000-000000000001
		sourceColumn: Brand
		summarizeBy: none

	column UnitPrice
		dataType: decimal
		lineageTag: pr000003-0006-0000-0000-000000000001
		sourceColumn: UnitPrice
		summarizeBy: average
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column CostPrice
		dataType: decimal
		lineageTag: pr000003-0007-0000-0000-000000000001
		sourceColumn: CostPrice
		summarizeBy: average
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column Status
		dataType: string
		lineageTag: pr000003-0008-0000-0000-000000000001
		sourceColumn: Status
		summarizeBy: none

	partition 'DimProduct-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "products.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"ProductID",   type text},
				        {"ProductName", type text},
				        {"Category",    type text},
				        {"Subcategory", type text},
				        {"Brand",       type text},
				        {"UnitPrice",   type number},
				        {"CostPrice",   type number},
				        {"Status",      type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
