table DimRegion
	lineageTag: rg000004-0000-0000-0000-000000000001

	column RegionID
		dataType: int64
		isHidden
		lineageTag: rg000004-0001-0000-0000-000000000001
		sourceColumn: RegionID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: rg000004-0002-0000-0000-000000000001
		sourceColumn: RegionName
		summarizeBy: none

	column Continent
		dataType: string
		lineageTag: rg000004-0003-0000-0000-000000000001
		sourceColumn: Continent
		summarizeBy: none

	column Zone
		dataType: string
		lineageTag: rg000004-0004-0000-0000-000000000001
		sourceColumn: Zone
		summarizeBy: none

	column SalesTarget
		dataType: decimal
		lineageTag: rg000004-0005-0000-0000-000000000001
		sourceColumn: SalesTarget
		summarizeBy: sum
		formatString: $ #,##0

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	partition 'DimRegion-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "regions.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"RegionID",     Int64.Type},
				        {"RegionName",   type text},
				        {"Continent",    type text},
				        {"Zone",         type text},
				        {"SalesTarget",  type number}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
