table FactReturns
	lineageTag: fr000006-0000-0000-0000-000000000001

	column ReturnID
		dataType: string
		lineageTag: fr000006-0001-0000-0000-000000000001
		sourceColumn: ReturnID
		summarizeBy: none

	column SalesID
		dataType: string
		isHidden
		lineageTag: fr000006-0002-0000-0000-000000000001
		sourceColumn: SalesID
		summarizeBy: none

	column DateID
		dataType: int64
		isHidden
		lineageTag: fr000006-0003-0000-0000-000000000001
		sourceColumn: DateID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		isHidden
		lineageTag: fr000006-0004-0000-0000-000000000001
		sourceColumn: CustomerID
		summarizeBy: none

	column ProductID
		dataType: string
		isHidden
		lineageTag: fr000006-0005-0000-0000-000000000001
		sourceColumn: ProductID
		summarizeBy: none

	column RegionID
		dataType: int64
		isHidden
		lineageTag: fr000006-0006-0000-0000-000000000001
		sourceColumn: RegionID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: fr000006-0007-0000-0000-000000000001
		sourceColumn: Quantity
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column RefundAmount
		dataType: decimal
		lineageTag: fr000006-0008-0000-0000-000000000001
		sourceColumn: RefundAmount
		summarizeBy: sum
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column ReturnReason
		dataType: string
		lineageTag: fr000006-0009-0000-0000-000000000001
		sourceColumn: ReturnReason
		summarizeBy: none

	partition 'FactReturns-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "returns.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"ReturnID",     type text},
				        {"SalesID",      type text},
				        {"DateID",       Int64.Type},
				        {"CustomerID",   type text},
				        {"ProductID",    type text},
				        {"RegionID",     Int64.Type},
				        {"Quantity",     Int64.Type},
				        {"RefundAmount", type number},
				        {"ReturnReason", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
