table FactSales
	lineageTag: fs000005-0000-0000-0000-000000000001

	column SalesID
		dataType: string
		lineageTag: fs000005-0001-0000-0000-000000000001
		sourceColumn: SalesID
		summarizeBy: none

	column DateID
		dataType: int64
		isHidden
		lineageTag: fs000005-0002-0000-0000-000000000001
		sourceColumn: DateID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		isHidden
		lineageTag: fs000005-0003-0000-0000-000000000001
		sourceColumn: CustomerID
		summarizeBy: none

	column ProductID
		dataType: string
		isHidden
		lineageTag: fs000005-0004-0000-0000-000000000001
		sourceColumn: ProductID
		summarizeBy: none

	column RegionID
		dataType: int64
		isHidden
		lineageTag: fs000005-0005-0000-0000-000000000001
		sourceColumn: RegionID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: fs000005-0006-0000-0000-000000000001
		sourceColumn: Quantity
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		lineageTag: fs000005-0007-0000-0000-000000000001
		sourceColumn: UnitPrice
		summarizeBy: average
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column DiscountPct
		dataType: decimal
		lineageTag: fs000005-0008-0000-0000-000000000001
		sourceColumn: DiscountPct
		summarizeBy: average
		formatString: 0.00%

		annotation SummarizationSetBy = Automatic

	column DiscountAmount
		dataType: decimal
		lineageTag: fs000005-0009-0000-0000-000000000001
		sourceColumn: DiscountAmount
		summarizeBy: sum
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column TotalAmount
		dataType: decimal
		lineageTag: fs000005-0010-0000-0000-000000000001
		sourceColumn: TotalAmount
		summarizeBy: sum
		formatString: $ #,##0.00

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencySymbol":"$"}

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: fs000005-0011-0000-0000-000000000001
		sourceColumn: OrderDate
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'FactSales-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "orders.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"SalesID",        type text},
				        {"DateID",         Int64.Type},
				        {"CustomerID",     type text},
				        {"ProductID",      type text},
				        {"RegionID",       Int64.Type},
				        {"Quantity",       Int64.Type},
				        {"UnitPrice",      type number},
				        {"DiscountPct",    type number},
				        {"DiscountAmount", type number},
				        {"TotalAmount",    type number},
				        {"OrderDate",      type date}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
