table FactInventory
	lineageTag: fi000007-0000-0000-0000-000000000001

	column InventoryID
		dataType: int64
		isHidden
		lineageTag: fi000007-0001-0000-0000-000000000001
		sourceColumn: InventoryID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DateID
		dataType: int64
		isHidden
		lineageTag: fi000007-0002-0000-0000-000000000001
		sourceColumn: DateID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		isHidden
		lineageTag: fi000007-0003-0000-0000-000000000001
		sourceColumn: ProductID
		summarizeBy: none

	column RegionID
		dataType: int64
		isHidden
		lineageTag: fi000007-0004-0000-0000-000000000001
		sourceColumn: RegionID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column QuantityOnHand
		dataType: int64
		lineageTag: fi000007-0005-0000-0000-000000000001
		sourceColumn: QuantityOnHand
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column QuantityOnOrder
		dataType: int64
		lineageTag: fi000007-0006-0000-0000-000000000001
		sourceColumn: QuantityOnOrder
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MonthlyUsage
		dataType: int64
		lineageTag: fi000007-0007-0000-0000-000000000001
		sourceColumn: MonthlyUsage
		summarizeBy: average

		annotation SummarizationSetBy = Automatic

	partition 'FactInventory-Partition' = m
		mode: import
		source =
				let
				    Source  = Csv.Document(
				        File.Contents(DataFolderPath & "inventory.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed   = Table.TransformColumnTypes(Headers, {
				        {"InventoryID",     Int64.Type},
				        {"DateID",          Int64.Type},
				        {"ProductID",       type text},
				        {"RegionID",        Int64.Type},
				        {"QuantityOnHand",  Int64.Type},
				        {"QuantityOnOrder", Int64.Type},
				        {"MonthlyUsage",    Int64.Type}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
