table _FinanceMeasures
	isHidden
	lineageTag: fm000007-0000-0000-0000-000000000001


	measure Actuals = SUM(FactActuals[Amount])
		formatString: #,##0
		lineageTag: fm000007-0101-0000-0000-000000000001

	measure Budget =
			CALCULATE(
			    SUM(FactBudget[BudgetAmount]),
			    FactBudget[BudgetVersion] = "Original Budget"
			)
		formatString: #,##0
		lineageTag: fm000007-0102-0000-0000-000000000001

	measure Variance = [Actuals] - [Budget]
		formatString: +#,##0;-#,##0;0
		lineageTag: fm000007-0103-0000-0000-000000000001

	measure 'Variance %' = DIVIDE([Variance], [Budget])
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: fm000007-0104-0000-0000-000000000001


	measure 'YTD Actuals' =
			CALCULATE(
			    [Actuals],
			    DATESYTD(DimPeriod[PeriodEndDate])
			)
		formatString: #,##0
		lineageTag: fm000007-0201-0000-0000-000000000001

	measure 'YTD Budget' =
			CALCULATE(
			    [Budget],
			    DATESYTD(DimPeriod[PeriodEndDate])
			)
		formatString: #,##0
		lineageTag: fm000007-0202-0000-0000-000000000001

	measure 'YTD Variance' = [YTD Actuals] - [YTD Budget]
		formatString: +#,##0;-#,##0;0
		lineageTag: fm000007-0203-0000-0000-000000000001

	measure 'YTD Variance %' = DIVIDE([YTD Variance], [YTD Budget])
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: fm000007-0204-0000-0000-000000000001


	measure 'Prior Year Actuals' =
			CALCULATE(
			    [Actuals],
			    DATEADD(DimPeriod[PeriodEndDate], -1, YEAR)
			)
		formatString: #,##0
		lineageTag: fm000007-0301-0000-0000-000000000001

	measure 'YoY Change' = [Actuals] - [Prior Year Actuals]
		formatString: +#,##0;-#,##0;0
		lineageTag: fm000007-0302-0000-0000-000000000001

	measure 'YoY Change %' = DIVIDE([YoY Change], [Prior Year Actuals])
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: fm000007-0303-0000-0000-000000000001


	measure Revenue =
			CALCULATE(
			    [Actuals],
			    DimAccount[AccountType] = "Revenue"
			)
		formatString: #,##0
		lineageTag: fm000007-0401-0000-0000-000000000001

	measure 'Cost of Goods Sold' =
			CALCULATE(
			    [Actuals],
			    DimAccount[AccountClass] = "Cost of Goods Sold"
			)
		formatString: #,##0
		lineageTag: fm000007-0402-0000-0000-000000000001

	measure 'Gross Profit (Finance)' = [Revenue] - [Cost of Goods Sold]
		formatString: #,##0
		lineageTag: fm000007-0403-0000-0000-000000000001

	measure 'Gross Margin % (Finance)' =
			DIVIDE([Gross Profit (Finance)], [Revenue])
		formatString: 0.0%
		lineageTag: fm000007-0404-0000-0000-000000000001

	measure 'Operating Expenses' =
			CALCULATE(
			    [Actuals],
			    DimAccount[AccountType] = "Expense",
			    DimAccount[AccountClass] = "Operating Expense"
			)
		formatString: #,##0
		lineageTag: fm000007-0405-0000-0000-000000000001

	measure EBITDA =
			[Gross Profit (Finance)] - [Operating Expenses]
		formatString: #,##0
		lineageTag: fm000007-0406-0000-0000-000000000001

	measure 'EBITDA Margin %' =
			DIVIDE([EBITDA], [Revenue])
		formatString: 0.0%
		lineageTag: fm000007-0407-0000-0000-000000000001

	measure 'Net Income' =
			[Revenue]
			    - CALCULATE(
			        [Actuals],
			        DimAccount[IsIncomeStatement] = TRUE,
			        DimAccount[AccountType] = "Expense"
			    )
		formatString: #,##0
		lineageTag: fm000007-0408-0000-0000-000000000001

	measure 'Net Margin %' =
			DIVIDE([Net Income], [Revenue])
		formatString: 0.0%
		lineageTag: fm000007-0409-0000-0000-000000000001

	partition '_FinanceMeasures-Partition' = m
		mode: import
		source =
				let
				    Source = #table(type table [], {})
				in
				    Source

	annotation PBI_ResultType = Table
