table DimPeriod
	lineageTag: pe000003-0000-0000-0000-000000000001
	dataCategory: Time

	column PeriodKey
		dataType: int64
		isHidden
		lineageTag: pe000003-0001-0000-0000-000000000001
		sourceColumn: PeriodKey
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PeriodCode
		dataType: string
		lineageTag: pe000003-0002-0000-0000-000000000001
		sourceColumn: PeriodCode
		summarizeBy: none

		sortByColumn: PeriodKey

	column Year
		dataType: int64
		lineageTag: pe000003-0003-0000-0000-000000000001
		sourceColumn: Year
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		lineageTag: pe000003-0004-0000-0000-000000000001
		sourceColumn: Quarter
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: pe000003-0005-0000-0000-000000000001
		sourceColumn: Month
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: pe000003-0006-0000-0000-000000000001
		sourceColumn: MonthName
		summarizeBy: none

		sortByColumn: Month

	column FiscalYear
		dataType: int64
		lineageTag: pe000003-0007-0000-0000-000000000001
		sourceColumn: FiscalYear
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FiscalPeriod
		dataType: int64
		lineageTag: pe000003-0008-0000-0000-000000000001
		sourceColumn: FiscalPeriod
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PeriodStartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: pe000003-0009-0000-0000-000000000001
		sourceColumn: PeriodStartDate
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PeriodEndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: pe000003-0010-0000-0000-000000000001
		sourceColumn: PeriodEndDate
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsCurrentPeriod
		dataType: boolean
		lineageTag: pe000003-0011-0000-0000-000000000001
		sourceColumn: IsCurrentPeriod
		summarizeBy: none

	partition 'DimPeriod-Partition' = m
		mode: import
		source =
				let
				    StartYear  = 2021,
				    EndYear    = 2026,
				    TodayDate  = DateTime.Date(DateTime.LocalNow()),
				    Months     = List.Generate(
				        () => #date(StartYear, 1, 1),
				        each Date.Year(_) < EndYear or (Date.Year(_) = EndYear and Date.Month(_) <= 4),
				        each Date.AddMonths(_, 1)
				    ),
				    ToRecord   = List.Transform(
				        List.Zip({List.Numbers(1, List.Count(Months)), Months}),
				        (pair) =>
				            let
				                key   = pair{0},
				                dt    = pair{1},
				                yr    = Date.Year(dt),
				                mo    = Date.Month(dt),
				                fmo   = Number.Mod(mo - 4 + 12, 12) + 1,
				                fyr   = if mo >= 4 then yr + 1 else yr,
				                edate = Date.EndOfMonth(dt)
				            in [
				                PeriodKey      = key,
				                PeriodCode     = Text.From(yr) & "-" & Text.PadStart(Text.From(mo), 2, "0"),
				                Year           = yr,
				                Quarter        = Number.IntegerDivide(mo - 1, 3) + 1,
				                Month          = mo,
				                MonthName      = Date.ToText(dt, "MMMM"),
				                FiscalYear     = fyr,
				                FiscalPeriod   = fmo,
				                PeriodStartDate = dt,
				                PeriodEndDate   = edate,
				                IsCurrentPeriod = (yr = Date.Year(TodayDate) and mo = Date.Month(TodayDate))
				            ]
				    ),
				    Table = Table.FromRecords(
				        ToRecord,
				        type table [
				            PeriodKey = Int64.Type,
				            PeriodCode = type text,
				            Year = Int64.Type,
				            Quarter = Int64.Type,
				            Month = Int64.Type,
				            MonthName = type text,
				            FiscalYear = Int64.Type,
				            FiscalPeriod = Int64.Type,
				            PeriodStartDate = type date,
				            PeriodEndDate = type date,
				            IsCurrentPeriod = type logical
				        ]
				    )
				in
				    Table

	annotation PBI_ResultType = Table
