table FactBudget
	lineageTag: fb000006-0000-0000-0000-000000000001

	column BudgetID
		dataType: int64
		isHidden
		lineageTag: fb000006-0001-0000-0000-000000000001
		sourceColumn: BudgetID
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: int64
		isHidden
		lineageTag: fb000006-0002-0000-0000-000000000001
		sourceColumn: AccountKey
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DepartmentKey
		dataType: int64
		isHidden
		lineageTag: fb000006-0003-0000-0000-000000000001
		sourceColumn: DepartmentKey
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PeriodKey
		dataType: int64
		isHidden
		lineageTag: fb000006-0004-0000-0000-000000000001
		sourceColumn: PeriodKey
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column EntityKey
		dataType: int64
		isHidden
		lineageTag: fb000006-0005-0000-0000-000000000001
		sourceColumn: EntityKey
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BudgetAmount
		dataType: decimal
		lineageTag: fb000006-0006-0000-0000-000000000001
		sourceColumn: BudgetAmount
		summarizeBy: sum
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column BudgetVersion
		dataType: string
		lineageTag: fb000006-0007-0000-0000-000000000001
		sourceColumn: BudgetVersion
		summarizeBy: none

	partition 'FactBudget-Partition' = m
		mode: import
		source =
				let
				    // Simulated budget data — replace with live planning system connection in production
				    Seed = List.Generate(
				        () => 1,
				        each _ <= 3000,
				        each _ + 1,
				        each [
				            BudgetID      = _,
				            AccountKey    = Number.Mod(_, 12) + 1,
				            DepartmentKey = Number.Mod(_ * 2, 12) + 1,
				            PeriodKey     = Number.Mod(_, 63) + 1,
				            EntityKey     = Number.Mod(_, 5) + 1,
				            BudgetAmount  = Number.Round((_ * 1500.00) / (Number.Mod(_, 5) + 1), 2),
				            BudgetVersion = if Number.Mod(_, 3) = 0 then "Original Budget"
				                            else if Number.Mod(_, 3) = 1 then "Revised Budget"
				                            else "Latest Forecast"
				        ]
				    ),
				    Source = Table.FromRecords(
				        Seed,
				        type table [
				            BudgetID = Int64.Type,
				            AccountKey = Int64.Type,
				            DepartmentKey = Int64.Type,
				            PeriodKey = Int64.Type,
				            EntityKey = Int64.Type,
				            BudgetAmount = type number,
				            BudgetVersion = type text
				        ]
				    )
				in
				    Source

	annotation PBI_ResultType = Table
